### ISSUE TITLE
parsing KB Documents

### ISSUE THREAD

**Issue by jm-nab** [MyPureCloud/knowledge-html-converter#1]
Is the October ETA still on track? When in October if so?

I didn't want to duplicate work by writing a custom parser, if this will be released soon.

See: https://developer.genesys.cloud/forum/t/create-knowledge-base-article-with-api/21995/6?u=jam

**Comment by tmelko-genesys** [comment]
Hi, I have published the package to npm: https://www.npmjs.com/package/knowledge-html-converter. Please, have a look.

**Comment by jm-nab** [comment]
@tmelko-genesys Thank you so much! I'll definitely give this a test drive this week.
