### ISSUE TITLE
ignoring Data

### ISSUE THREAD

**Issue by slindsay23** [MyPureCloud/knowledge-html-converter#3]
We have come across various issues with this package and had to update a decent amount, we found that it leaves out the data from Platform A (Old platform) due to the config files being incorrect. I would say if you are using this be prepared to make a lot of changes to the config files, maybe even consider writing this from scratch.

**Comment by tmelko-genesys** [comment]
Yes, unfortunately there are two places where information can be lost:
- the json schema which describes articles in the Genesys Knowledge API is much more limited than html, so it constrains which html elements or css inline styles we can transform.
- even if the json schema could describe a certain html element or css style, we might have not included it in the transformation.

Altogether, this converter package performs very badly with highly styled html, ignoring most elements and style attributes, but we hoped that it could be sufficient for FAQ articles which usually don't have that much styling.

Is there any specific issue we should look at? Which config files are incorrect?

**Comment by tmelko-genesys** [comment]
I'm closing this issue. Let us know if there is a specific issue we should look at.

**Comment by tmelko-genesys** [comment]
I'm closing this issue. Let us know if there is a specific issue we should look at.
